name: Build and Tag Docker Image
on:
  push:
    branches:
      - main

jobs:
  build-and-tag:
    runs-on: ubuntu-latest
    env:
      JFROG_CLI_BUILD_NAME: jfrog-docker-build-example
      JFROG_CLI_BUILD_NUMBER: ${{ github.run_number }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}

      # Docker steps
      - name: Build Tag and push Docker Image
        env:
          IMAGE_NAME: trialdhioxf.jfrog.io/sample-docker/jfrog-docker-example-image:${{ github.run_number }}
        run: |
          jf docker build -f docker/Dockerfile -t $IMAGE_NAME .
          jf docker push $IMAGE_NAME

      # NPM steps
      - name: Setup Node npm
        uses: actions/setup-node@v3

      - name: Set CLI Config
        run: jf npm-config --global=true --repo-resolve=jfrog-sample-npm --repo-deploy=jfrog-sample-npm

      - name: Install Deps
        run: |
          cd app  
          jf npm install

      - name: Run tests
        run: npm test

      - name: Publish NPM
        run: jf npm publish

      # Publish all build info together at the end
      - name: Publish Build info With JFrog CLI
        run: |
          jf rt build-collect-env
          jf rt build-add-git
          jf rt build-publish
